### ISSUE TITLE
关于pom.xml的问题，有一个报错，已解决

### ISSUE THREAD

**Issue by jiale233** [Zjh-project/sms#42]
就是我在导入项目的时候pom那里报错了，chatgpt一下之后发现是位置放错了，调整之后就好了。
需要把这一段从<properties>中移到外面来，他们不可以放在这里面
<repositories>
		<repository>
			<id>alimaven</id>
			<url>https://maven.aliyun.com/repository/public</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>alimaven</id>
			<url>https://maven.aliyun.com/repository/public</url>
		</pluginRepository>
	</pluginRepositories>

**Comment by tomjackwww** [comment]
请问你跑起来了吗？

**Comment by WY191** [comment]
是需要将整个repositories和pluginRepositories都放到project下面，而不是在properties下
<img width="353" alt="20231124165750" src="https://github.com/by-night/sms/assets/130282877/5d1954b2-4421-4b39-879c-6df3e22628e7">
